/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */

  mySidebar: [
    {
      type: 'doc',
      id: 'introduction',
      label: 'Introduction'
    },

    {
      type: 'category',
      label: 'General',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'general/getting-started',
          label: 'Getting Started'
        },
        {
          type: 'doc',
          id: 'general/api-keys',
          label: 'API Keys'
        },
        {
          type: 'doc',
          id: 'general/faq',
          label: 'FAQ'
        },
      ]
    },
    {
      type: 'category',
      label: 'Pinning API',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'pinning/pin-file',
          label: 'pinFile'
        },
        {
          type: 'doc',
          id: 'pinning/pin-by-hash',
          label: 'pinByHash'
        },
        {
          type: 'doc',
          id: 'pinning/pin-jobs',
          label: 'pinJobs'
        },
        {
          type: 'doc',
          id: 'pinning/pin-list',
          label: 'pinList'
        },
      ]
    },
    {
      type: 'doc',
      id: 'pinning-services-api',
      label: 'IPFS Remote Pinning Services API'
    }

  ]

};
